apiVersion: v1
kind: Service
metadata:
  name: projet-j2ee-service
spec:
  selector:
    app: tomcat 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110
